{% set version = '0.0.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fastglm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fastglm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fastglm/fastglm_{{ version }}.tar.gz
  sha256: 51281bb1a445be0921a48e1ec98edbf3d7f2f0cfe156494f8cabb380e69b0309

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-rcpp >=0.12.13
    - r-rcppeigen
    - r-bigmemory
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-bh
    - r-rcpp >=0.12.13
    - r-rcppeigen
    - r-bigmemory

test:
  commands:
    - $R -e "library('fastglm')"           # [not win]
    - "\"%R%\" -e \"library('fastglm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=fastglm
  license: GPL-2.0-or-later
  summary: Fits generalized linear models efficiently using 'RcppEigen'. The iteratively reweighted
    least squares implementation utilizes the step-halving approach of Marschner (2011)
    <doi:10.32614/RJ-2011-012> to help safeguard against convergence issues.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: fastglm
# Type: Package
# Title: Fast and Stable Fitting of Generalized Linear Models using 'RcppEigen'
# Version: 0.0.3
# Authors@R: c( person("Jared", "Huling", , "jaredhuling@gmail.com", c("aut", "cre")), person("Douglas", "Bates", , , c("cph")), person("Dirk", "Eddelbuettel", , , c("cph")), person("Romain", "Francois", , , c("cph")), person("Yixuan", "Qiu", , , c("cph")) )
# Maintainer: Jared Huling <jaredhuling@gmail.com>
# Description: Fits generalized linear models efficiently using 'RcppEigen'. The iteratively reweighted least squares implementation utilizes the step-halving approach of Marschner (2011) <doi:10.32614/RJ-2011-012> to help safeguard against convergence issues.
# BugReports: https://github.com/jaredhuling/fastglm/issues
# License: GPL (>= 2)
# Encoding: UTF-8
# Imports: Rcpp (>= 0.12.13), methods
# Depends: bigmemory
# LinkingTo: Rcpp, RcppEigen, BH, bigmemory
# RoxygenNote: 7.1.1
# Suggests: knitr, rmarkdown, glm2
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2022-05-23 15:40:18 UTC; huling
# Author: Jared Huling [aut, cre], Douglas Bates [cph], Dirk Eddelbuettel [cph], Romain Francois [cph], Yixuan Qiu [cph]
# Repository: CRAN
# Date/Publication: 2022-05-23 16:50:02 UTC
